substitutions:
  _REGION: us-east1
  _PROJECT_ID: project-045a9bc2-2b2f-428e-9c0
  _REPOSITORY_NAME: demo-repo
  _SERVICE_NAME: qa-be-staging
  _REPOSITORY_URI: us-east1-docker.pkg.dev/project-045a9bc2-2b2f-428e-9c0/demo-repo/qa-be-staging
  _IMAGE_TAG: $SHORT_SHA

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '--no-cache'
      - '-t'
      - '${_REPOSITORY_URI}:${_IMAGE_TAG}'
      - '-t'
      - '${_REPOSITORY_URI}:latest'
      - '.'

  # Step 2: Push images to Artifact Registry
  # Explicit push ensures the image exists before Cloud Run tries to pull it
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', '--all-tags', '${_REPOSITORY_URI}']

  # Step 3: Deploy to Cloud Run (Staging Environment)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REPOSITORY_URI}:${_IMAGE_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Linking images to the build for history and traceability
images:
  - '${_REPOSITORY_URI}:${_IMAGE_TAG}'
  - '${_REPOSITORY_URI}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
