substitutions:
  _REPOSITORY_URI: us-east1-docker.pkg.dev/project-045a9bc2-2b2f-428e-9c0/demo-repo/qa-be
  _IMAGE_TAG: $SHORT_SHA

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '--no-cache'
      - '-t'
      - '${_REPOSITORY_URI}:${_IMAGE_TAG}'
      - '-t'
      - '${_REPOSITORY_URI}:latest'
      - '.'

  # Step 2: Generate imagedefinitions.json using Cloud SDK
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        printf '[{"name":"qa-be-dev","imageUri":"%s"}]' \
        "${_REPOSITORY_URI}:${_IMAGE_TAG}" > imagedefinitions.json

# Pushes images to Artifact Registry
images:
  - '${_REPOSITORY_URI}:${_IMAGE_TAG}'
  - '${_REPOSITORY_URI}:latest'

# Uploads artifacts to GCS
artifacts:
  objects:
    location: 'gs://demo-build-artifacts/dev'
    paths:
      - 'imagedefinitions.json'
