substitutions:
  _REGION: us-east1
  _SERVICE_NAME: qa-be-prod
  _REPOSITORY_URI: us-east1-docker.pkg.dev/project-045a9bc2-2b2f-428e-9c0/demo-repo/qa-be
  _IMAGE_TAG: $SHORT_SHA

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '--no-cache'
      - '-t'
      - '${_REPOSITORY_URI}:${_IMAGE_TAG}'
      - '-t'
      - '${_REPOSITORY_URI}:latest'
      - '.'

  # Step 2: Push images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', '--all-tags', '${_REPOSITORY_URI}']

  # Step 3: Deploy to Cloud Run (Production)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REPOSITORY_URI}:${_IMAGE_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      # Production services are usually private or behind a Load Balancer. 
      # Remove '--allow-unauthenticated' if this is an internal API.
      - '--allow-unauthenticated' 

# Record the production images for auditing
images:
  - '${_REPOSITORY_URI}:${_IMAGE_TAG}'
  - '${_REPOSITORY_URI}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
