substitutions:
  _REPOSITORY_URI: us-east1-docker.pkg.dev/project-045a9bc2-2b2f-428e-9c0/demo-repo/qa-be
  _IMAGE_TAG: $SHORT_SHA

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform=linux/amd64
      - -t
      - ${_REPOSITORY_URI}:${_IMAGE_TAG}
      - -t
      - ${_REPOSITORY_URI}:latest
      - .
    dir: QA-app

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REPOSITORY_URI}:latest

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REPOSITORY_URI}:${_IMAGE_TAG}

  - name: gcr.io/cloud-builders/bash
    args:
      - -c
      - |
        printf '[{"name":"qa-be-dev","imageUri":"%s"}]' \
        "${_REPOSITORY_URI}:${_IMAGE_TAG}" > imagedefinitions.json

artifacts:
  objects:
    location: gs://demo-build-artifacts
    paths:
      - imagedefinitions.json
